---
grpcport: 50151
httpport: 8082
tlsfiles:
database: redis
dbaddress: 127.0.0.1:6379
buildenv: intel_e2000
tracer: false
subscribers:
  - name: "lvm"
    priority: 2
    events: ["vrf", "bridge-port"]
  - name: "lgm"
    priority: 1
    events: ["vrf", "svi", "logical-bridge"]
  - name: "frr"
    priority: 3
    events: ["vrf", "svi"]
  - name: "intel-e2000"
    priority: 4
    events: ["vrf", "logical-bridge", "bridge-port", "svi"]
grpc:
  server_addresses:
    - 0.0.0.0
  server_port: 51703
  num_threads: 10
  static_external_macs: []
interfaces:
  phyports:
    - rep: "enp0s1f0d1"
      vsi: 0
    - rep: "enp0s1f0d3"
      vsi: 1
  grpcacc: "enp0s1f0d2"
  grpchost: "00:0d:00:03:09:64"
  vrfmux: "enp0s1f0d4"
  portmux: "enp0s1f0d5"
p4:
  enabled: true
  config:
    p4infofile: /root/networking.ethernet.acceleration.mev.infra.joint/gw_integration/p4files/evpn_gw.p4info.txt
    binfile: /root/networking.ethernet.acceleration.mev.infra.joint/gw_integration/p4files/evpn_gw.pb.bin
linuxfrr:
  enabled: true
  defaultvtep: "vxlan-vtep"
  ipmtu: 2962
  localas: 65011
netlink:
  enabled: true
  pollinterval: 1
  grddefaultroute: false
  enableecmp: true
loglevel:
  db: INFO
  grpc: INFO
  linux: INFO
  netlink: INFO
  p4: DEBUG
