name: EClint

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  eclint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: snow-actions/eclint@73be49ca24c9def5248c40e4b2fd1976c9d58a3a # v1.0.1
        with:
          args: 'check'
