name: EClint

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  eclint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: snow-actions/eclint@73be49ca24c9def5248c40e4b2fd1976c9d58a3a # v1.0.1
        with:
          args: 'check'
