name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions: read-all

jobs:
  release-docker:
    permissions:
      packages: write
      id-token: write
      contents: read
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit
