name: OpenSSF

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  call:
    uses: opiproject/opi-smbios-bridge/.github/workflows/scorecard.yml@main
    secrets: inherit
