name: OpenSSF

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: read-all

jobs:
  call:
    permissions:
      security-events: write
      id-token: write
      actions: read
      contents: read
    uses: opiproject/actions/.github/workflows/scorecard.yml@main
    secrets: inherit
